name: "Import INSEE Data to Azure"

on:
  workflow_dispatch:  # Déclenchement manuel
  schedule:
    - cron: '0 0 1 * *'  # Le 1er de chaque mois à minuit (00:00)

jobs:
  check-and-import:
    name: "Check and Import Data from INSEE"
    runs-on: ubuntu-latest

    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    defaults:
      run:
        working-directory: ./prod/import

    steps:
      - name: 🛎 Checkout Repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 📥 Import Data
        id: import
        run: python import_insee.py

      - name: 📋 Check Import Status
        id: check
        run: |
          if [ -f "skip_import" ]; then
            echo "Aucun import nécessaire - Les fichiers existent déjà"
            echo "skipped=true" >> $GITHUB_OUTPUT
          else
            echo "Import effectué avec succès"
            echo "skipped=false" >> $GITHUB_OUTPUT
          fi