name: Move and Clean CSV

on:
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}

    steps:
      - name: 📥 Checkout du code
        uses: actions/checkout@v3

      - name: 🐍 Configuration de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r prod/pipeline/requirements.txt

      - name: ▶️ Exécution du script move_and_clean_csv.py
        run: |
          python ./prod/pipeline/src/move_and_clean_csv.py
