name: Move and Clean CSV

on:
  workflow_dispatch:  # Déclenchement manuel via l'interface GitHub

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout du code
        uses: actions/checkout@v3

      - name: 🐍 Configuration de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r prod/pipeline/requirements.txt

      - name: 🔐 Connexion à Azure avec les identifiants
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        run: |
          echo "Connexion Azure configurée avec les identifiants secrets"

      - name: ▶️ Exécution du script move_and_clean_csv.py
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        run: |
          python ./prod/pipeline/src/move_and_clean_csv.py
