name: "Pipeline Data Cleaning"

on:
  schedule:
    - cron: "0 0 1 * *"  # Tous les jours à minuit
  workflow_dispatch:  # Déclenchement manuel

jobs:
  clean-and-move:
    runs-on: ubuntu-latest

    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: 🛎 Checkout Repository
        uses: actions/checkout@v3

      - name: 📦 Installer les dépendances
        run: pip install -r requirements.txt

      - name: 🚀 Exécuter le pipeline
        run: python src/pipeline.py
