name: "Pipeline Data Cleaning"

on:
  schedule:
    - cron: "0 0 1 * *"  # Exécution automatique chaque mois
  workflow_dispatch:  # Déclenchement manuel

jobs:
  clean-and-move:
    runs-on: ubuntu-latest

    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}

    # defaults:
    #   run:
    #     working-directory: ./prod/pipeline/src

    steps:
      - name: 🛎 Checkout Repository
        uses: actions/checkout@v3

      - name: 📦 Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r prod/pipeline/requirements.txt

      - name: 🔐 Connexion à Azure avec le Service Principal
        run: az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID

      - name: 🚀 Exécuter le pipeline
        run: python prod/pipeline/src/pipeline.py
